name: React build
on: 
  push:     
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: main
        uses: actions/checkout@main

      - name: npm install
        run: npm install

      - name: Build                   
        run: npm run build