name: React build
on: 
  push:     
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: develop
        uses: actions/checkout@develop

      - name: npm install
        run: npm install

      - name: Build                   
        run: npm run build